FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Create and set work directory
WORKDIR /app

# Install Python dependencies
COPY requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.dev.txt

# Make entrypoint script executable
COPY entrypoint.dev.sh .
RUN chmod +x /app/entrypoint.dev.sh

# Expose port
EXPOSE 8000

# Run development server with live reload
CMD ["/app/entrypoint.dev.sh"]
