# Generated by Django 5.1.7 on 2025-03-12 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_roomparticipant_has_voted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='votingroom',
            name='participants',
            field=models.ManyToManyField(through='voting.RoomParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
