# Generated by Django 5.1.7 on 2025-03-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_votingroom_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
