# Generated by Django 5.1.7 on 2025-03-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_roomparticipant_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
