# Generated by Django 5.1.7 on 2025-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vote_rooms',
            field=models.ManyToManyField(blank=True, to='voting.votingroom'),
        ),
    ]
